# Simple Docker Compose for Sample Tracking
services:
  app:
    build: .
    container_name: sample_tracking
    ports:
      - "4567:4567"
    environment:
      - RACK_ENV=development
      - PORT=4567
      - HOST=0.0.0.0
    volumes:
      - .:/app
    working_dir: /app
